# Generated by Django 4.2.27 on 2026-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispensas", "0005_departamento_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="anexo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="anexos/",
                verbose_name="Comprovante/Anexo",
            ),
        ),
    ]
