# Generated by Django 4.2.27 on 2026-01-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=20)),
                ("cargo", models.CharField(max_length=100)),
                ("unidade", models.CharField(max_length=100)),
                (
                    "nome_evento",
                    models.CharField(max_length=200, verbose_name="Evento"),
                ),
                ("objetivo", models.TextField(verbose_name="Objetivo do Evento")),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(default="SP", max_length=2)),
                ("data_inicio", models.DateField(verbose_name="Início do Afastamento")),
                ("data_fim", models.DateField(verbose_name="Fim do Afastamento")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE_GERENTE", "Aguardando Gerência"),
                            ("PENDENTE_COORD", "Aguardando Coordenação"),
                            ("PENDENTE_ADMIN", "Aguardando Secretaria/RH"),
                            ("APROVADO", "Concluído"),
                            ("CANCELADO", "Indeferido"),
                        ],
                        default="PENDENTE_GERENTE",
                        max_length=20,
                    ),
                ),
                (
                    "gerente_assinatura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gerente_data", models.DateTimeField(blank=True, null=True)),
                (
                    "coord_assinatura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("coord_data", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_assinatura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("admin_data", models.DateTimeField(blank=True, null=True)),
                ("motivo_cancelamento", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Dispensa",
                "verbose_name_plural": "Solicitações de Dispensa",
            },
        ),
    ]
