# Generated by Django 4.2.27 on 2026-01-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={},
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='admin_assinatura',
            new_name='assinatura_admin',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='coord_assinatura',
            new_name='assinatura_coordenador',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='gerente_assinatura',
            new_name='assinatura_gerente',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='admin_data',
            new_name='data_aprovacao_admin',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='coord_data',
            new_name='data_aprovacao_coordenador',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='gerente_data',
            new_name='data_aprovacao_gerente',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='data_criacao',
            new_name='data_solicitacao',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='assinatura_servidor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='protocolo_sigm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo_convite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo_convocacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo_outros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo_programacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='nome_evento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='objetivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE_GERENTE', 'Aguardando Gerente'), ('PENDENTE_COORD', 'Aguardando Coordenação'), ('PENDENTE_ADMIN', 'Aguardando Secretaria'), ('APROVADO', 'Concluído'), ('CANCELADO', 'Indeferido')], default='PENDENTE_GERENTE', max_length=20),
        ),
    ]
