# Generated by Django 4.2.27 on 2026-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensas', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unidade',
            field=models.TextField(default='Não definida'),
        ),
    ]
